name: Run E2E tests

on: push

jobs:
  build:
    runs-on: windows10-22h2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
